### ISSUE TITLE
Unable to edit the hex on anything below "selection_backround"

### ISSUE THREAD

**Issue by TheDWPCer** [ARival/Kilocolor#1]
When you get to "section_foreground" and below, the color window goes off screen making it impossible to edit the hex codes on anything below that point.

**Comment by ARival** [comment]
Hmmm, I have been working on trying to find a decent fix; for now, use the arrow keys to scroll down when the color window appears.

**Comment by TheDWPCer** [comment]
Ah never thought of that thanks

**Comment by ARival** [comment]
Fixed in 2.0

**Comment by ARival** [comment]
9919c17cee04f6da464cc84fc103692e7f4f4f4b
